global:
  scrape_interval: 10m
  evaluation_interval: 10m

scrape_configs:
  - job_name: 'observability-example'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
